version: '3.7'

services:
  weather_app_django_backend:
    container_name: weather_app_django_backend    
    build:
      context: django_backend
      dockerfile: Dockerfile
    image: weather_app_django_backend
    ports:
      - "8000:8000"
    env_file: .env 
    volumes:
      - ./django_backend/app:/django_backend/app:cached 

  weather_app_caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: weather_app_caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - weather_app_django_backend


