version: '3.7'

services:
  weather_app_backend:
    container_name: weather_app_backend
    build:
      context: backend
      dockerfile: Dockerfile
    image: weather_app_backend
    ports:
      - "8000:8000"
    env_file: .env 
    volumes:
      - ./backend/app:/backend/app:cached 

  caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: weather_app_caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - weather_app_backend


