# Generated by Django 4.2.1 on 2023-05-14 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'locations'},
        ),
        migrations.RenameField(
            model_name='city',
            old_name='city_name',
            new_name='location',
        ),
    ]
